local addonName, addon = ...
local class = addon.class

-- Leveling weights (1-79)
local levelingWeights = {
    ["MAGE"] = {
        ["Arcane"] = { ITEM_MOD_INTELLECT_SHORT = 1.8, ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_HIT_RATING_SHORT = 1.5, ITEM_MOD_CRIT_RATING_SHORT = 0.9, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.6, ITEM_MOD_SPIRIT_SHORT = 0.3 },
        ["Fire"] = { ITEM_MOD_INTELLECT_SHORT = 1.7, ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.6, ITEM_MOD_SPIRIT_SHORT = 0.2 },
        ["Frost"] = { ITEM_MOD_INTELLECT_SHORT = 1.8, ITEM_MOD_SPELL_POWER_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_SPIRIT_SHORT = 0.3 },
        ["Specs"] = { "Arcane", "Fire", "Frost" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
    ["DEATHKNIGHT"] = {
        ["Blood"] = { ITEM_MOD_STR_SHORT = 2.4, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, RES_ARMOR = 1.7, ITEM_MOD_DEFENSE_RATING_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.7, ITEM_MOD_CRIT_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.7 },
        ["Frost"] = { ITEM_MOD_STR_SHORT = 2.2, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, RES_ARMOR = 0.05, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.7, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_CRIT_RATING_SHORT = 1.1 },
        ["Unholy"] = { ITEM_MOD_STR_SHORT = 2.1, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, RES_ARMOR = 0.05, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.6 },
        ["Specs"] = { "Blood", "Frost", "Unholy" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["WARRIOR"] = {
        ["Arms"] = { ITEM_MOD_STR_SHORT = 2.0, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 2.5, ITEM_MOD_CRIT_RATING_SHORT = 1.5, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.8, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 0.6 },
        ["Fury"] = { ITEM_MOD_STR_SHORT = 1.8, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 2.5, ITEM_MOD_CRIT_RATING_SHORT = 1.8, ITEM_MOD_HASTE_RATING_SHORT = 1.5, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.6, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.9 },
        ["Protection"] = { ITEM_MOD_STR_SHORT = 1.5, ITEM_MOD_STAMINA_SHORT = 1.2, RES_ARMOR = 0.2, ITEM_MOD_HIT_RATING_SHORT = 1.8, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.5, ITEM_MOD_DODGE_RATING_SHORT = 1.0, ITEM_MOD_PARRY_RATING_SHORT = 1.0 },
        ["Specs"] = { "Arms", "Fury", "Protection" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["PALADIN"] = {
        ["Holy"] = { ITEM_MOD_INTELLECT_SHORT = 1.0, ITEM_MOD_SPELL_POWER_SHORT = 1.0, ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.6, ITEM_MOD_CRIT_RATING_SHORT = 0.8, ITEM_MOD_HASTE_RATING_SHORT = 0.7, ITEM_MOD_MANA_REGEN_SHORT = 0.3, ITEM_MOD_SPIRIT_SHORT = 0.4 },
        ["Protection"] = { ITEM_MOD_STR_SHORT = 1.5, ITEM_MOD_STAMINA_SHORT = 1.2, RES_ARMOR = 0.15, ITEM_MOD_HIT_RATING_SHORT = 1.8, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.5, ITEM_MOD_DODGE_RATING_SHORT = 1.0, ITEM_MOD_PARRY_RATING_SHORT = 1.0 },
        ["Retribution"] = { ITEM_MOD_STR_SHORT = 1.8, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 2.3, ITEM_MOD_CRIT_RATING_SHORT = 1.4, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.6, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 0.8 },
        ["Specs"] = { "Holy", "Protection", "Retribution" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["PRIEST"] = {
        ["Discipline"] = { ITEM_MOD_INTELLECT_SHORT = 1.7, ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 0.9, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_SPIRIT_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Holy"] = { ITEM_MOD_INTELLECT_SHORT = 1.8, ITEM_MOD_SPELL_POWER_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 0.6, ITEM_MOD_SPIRIT_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Shadow"] = { ITEM_MOD_INTELLECT_SHORT = 1.8, ITEM_MOD_SPELL_POWER_SHORT = 1.5, ITEM_MOD_HIT_RATING_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_SPIRIT_SHORT = 0.6, ITEM_MOD_STAMINA_SHORT = 0.7 },
        ["Specs"] = { "Discipline", "Holy", "Shadow" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
    ["DRUID"] = {
        ["Balance"] = { ITEM_MOD_INTELLECT_SHORT = 0.9, ITEM_MOD_SPELL_POWER_SHORT = 1.0, ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.7, ITEM_MOD_CRIT_RATING_SHORT = 0.8, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_MANA_REGEN_SHORT = 0.2, ITEM_MOD_SPIRIT_SHORT = 0.3 },
        ["Feral"] = { ITEM_MOD_STR_SHORT = 2.379, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_AGILITY_SHORT = 2.1, ITEM_MOD_HIT_RATING_SHORT = 2.2, ITEM_MOD_CRIT_RATING_SHORT = 1.8, ITEM_MOD_HASTE_RATING_SHORT = 1.2, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.4, ITEM_MOD_FERAL_ATTACK_POWER_SHORT = 1.2 },
        ["Restoration"] = { ITEM_MOD_INTELLECT_SHORT = 1.0, ITEM_MOD_SPELL_POWER_SHORT = 1.0, ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_MANA_REGEN_SHORT = 0.6, ITEM_MOD_SPIRIT_SHORT = 0.7 },
        ["Specs"] = { "Balance", "Feral", "Restoration" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["ROGUE"] = {
        ["Assassination"] = { ITEM_MOD_AGILITY_SHORT = 1.8, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 2.4, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.6, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 0.7 },
        ["Combat"] = { ITEM_MOD_AGILITY_SHORT = 1.6, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 2.5, ITEM_MOD_CRIT_RATING_SHORT = 1.4, ITEM_MOD_HASTE_RATING_SHORT = 1.2, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.5, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.9 },
        ["Subtlety"] = { ITEM_MOD_AGILITY_SHORT = 1.7, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 2.3, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_EXPERTISE_RATING_SHORT = 1.5, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 0.8 },
        ["Specs"] = { "Assassination", "Combat", "Subtlety" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["HUNTER"] = {
        ["Beast Mastery"] = { ITEM_MOD_AGILITY_SHORT = 2.2, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_INTELLECT_SHORT = 0.5 },
        ["Marksmanship"] = { ITEM_MOD_AGILITY_SHORT = 2.0, ITEM_MOD_ATTACK_POWER_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.7, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.65 },
        ["Survival"] = { ITEM_MOD_AGILITY_SHORT = 2.1, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.8, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.65 },
        ["Specs"] = { "Beast Mastery", "Marksmanship", "Survival" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE
    },
    ["SHAMAN"] = {
        ["Elemental"] = { ITEM_MOD_INTELLECT_SHORT = 1.7, ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_HIT_RATING_SHORT = 1.5, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_SPIRIT_SHORT = 0.4 },
        ["Enhancement"] = { ITEM_MOD_AGILITY_SHORT = 2.0, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 0.7, ITEM_MOD_SPELL_POWER_SHORT = 0.5, ITEM_MOD_STAMINA_SHORT = 0.65 },
        ["Restoration"] = { ITEM_MOD_INTELLECT_SHORT = 1.8, ITEM_MOD_SPELL_POWER_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 0.9, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_SPIRIT_SHORT = 1.2, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Specs"] = { "Elemental", "Enhancement", "Restoration" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
    ["WARLOCK"] = {
        ["Affliction"] = { ITEM_MOD_INTELLECT_SHORT = 1.7, ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_HIT_RATING_SHORT = 1.5, ITEM_MOD_CRIT_RATING_SHORT = 0.8, ITEM_MOD_HASTE_RATING_SHORT = 0.7, ITEM_MOD_SPIRIT_SHORT = 0.5, ITEM_MOD_STAMINA_SHORT = 0.6, ITEM_MOD_MANA_REGEN_SHORT = 0.0 },
        ["Demonology"] = { ITEM_MOD_INTELLECT_SHORT = 1.7, ITEM_MOD_SPELL_POWER_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 0.9, ITEM_MOD_HASTE_RATING_SHORT = 0.7, ITEM_MOD_SPIRIT_SHORT = 0.3, ITEM_MOD_STAMINA_SHORT = 0.65, ITEM_MOD_MANA_REGEN_SHORT = 0.0 },
        ["Destruction"] = { ITEM_MOD_INTELLECT_SHORT = 1.6, ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HIT_RATING_SHORT = 1.4, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.6, ITEM_MOD_SPIRIT_SHORT = 0.0, ITEM_MOD_MANA_REGEN_SHORT = 0.0 },
        ["Specs"] = { "Affliction", "Demonology", "Destruction" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
}

-- Level 80 endgame weights
local endgameWeights = {
    ["MAGE"] = {
        ["Arcane"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.5, ITEM_MOD_INTELLECT_SHORT = 1.4, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_STAMINA_SHORT = 0.7 },
        ["Fire"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.5, ITEM_MOD_INTELLECT_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.7 },
        ["Frost"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_INTELLECT_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.1, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Specs"] = { "Arcane", "Fire", "Frost" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
    ["DEATHKNIGHT"] = {
        ["Blood"] = { ITEM_MOD_STAMINA_SHORT = 2.0, RES_ARMOR = 1.5, ITEM_MOD_DEFENSE_RATING_SHORT = 0.8, ITEM_MOD_STR_SHORT = 1.0, ITEM_MOD_DODGE_RATING_SHORT = 0.7, ITEM_MOD_PARRY_RATING_SHORT = 0.7, ITEM_MOD_HIT_RATING_SHORT = 0.0, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0, ITEM_MOD_ATTACK_POWER_SHORT = 0.0, ITEM_MOD_CRIT_RATING_SHORT = 0.0 },
        ["Frost"] = { ITEM_MOD_STR_SHORT = 2.2, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.8, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.1, ITEM_MOD_ATTACK_POWER_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.8, RES_ARMOR = 0.0, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Unholy"] = { ITEM_MOD_STR_SHORT = 1.9, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.9, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.0, ITEM_MOD_ATTACK_POWER_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Specs"] = { "Blood", "Frost", "Unholy" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["WARRIOR"] = {
        ["Arms"] = { ITEM_MOD_STR_SHORT = 2.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.8, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_ATTACK_POWER_SHORT = 0.5, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0, ITEM_MOD_AGILITY_SHORT = 0.0 },
        ["Fury"] = { ITEM_MOD_STR_SHORT = 1.8, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 2.0, ITEM_MOD_CRIT_RATING_SHORT = 1.4, ITEM_MOD_HASTE_RATING_SHORT = 1.2, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0, ITEM_MOD_AGILITY_SHORT = 0.0 },
        ["Protection"] = { ITEM_MOD_STAMINA_SHORT = 2.0, RES_ARMOR = 1.5, ITEM_MOD_DEFENSE_RATING_SHORT = 1.2, ITEM_MOD_BLOCK_RATING_SHORT = 1.4, ITEM_MOD_BLOCK_VALUE_SHORT = 1.4, ITEM_MOD_DODGE_RATING_SHORT = 0.9, ITEM_MOD_PARRY_RATING_SHORT = 0.8, ITEM_MOD_STR_SHORT = 0.0, ITEM_MOD_HIT_RATING_SHORT = 0.0, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Specs"] = { "Arms", "Fury", "Protection" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["PALADIN"] = {
        ["Holy"] = { ITEM_MOD_INTELLECT_SHORT = 1.0, ITEM_MOD_SPELL_POWER_SHORT = 1.0, ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.6, ITEM_MOD_CRIT_RATING_SHORT = 0.8, ITEM_MOD_HASTE_RATING_SHORT = 0.7, ITEM_MOD_MANA_REGEN_SHORT = 0.3, ITEM_MOD_SPIRIT_SHORT = 0.4 },
        ["Protection"] = { ITEM_MOD_STAMINA_SHORT = 1.9, RES_ARMOR = 1.4, ITEM_MOD_DEFENSE_RATING_SHORT = 1.0, ITEM_MOD_BLOCK_RATING_SHORT = 1.5, ITEM_MOD_BLOCK_VALUE_SHORT = 1.5, ITEM_MOD_DODGE_RATING_SHORT = 0.7, ITEM_MOD_PARRY_RATING_SHORT = 0.7, ITEM_MOD_STR_SHORT = 0.0, ITEM_MOD_HIT_RATING_SHORT = 0.0, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Retribution"] = { ITEM_MOD_STR_SHORT = 2.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.6, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_ATTACK_POWER_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_SPELL_POWER_SHORT = 0.0, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Specs"] = { "Holy", "Protection", "Retribution" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["PRIEST"] = {
        ["Discipline"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_INTELLECT_SHORT = 1.5, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_SPIRIT_SHORT = 0.7, ITEM_MOD_STAMINA_SHORT = 0.9 },
        ["Holy"] = { ITEM_MOD_INTELLECT_SHORT = 1.6, ITEM_MOD_SPELL_POWER_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_SPIRIT_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.9 },
        ["Shadow"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.6, ITEM_MOD_INTELLECT_SHORT = 1.4, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_CRIT_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Specs"] = { "Discipline", "Holy", "Shadow" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
    ["DRUID"] = {
        ["Balance"] = { ITEM_MOD_INTELLECT_SHORT = 0.9, ITEM_MOD_SPELL_POWER_SHORT = 1.0, ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.7, ITEM_MOD_CRIT_RATING_SHORT = 0.8, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_MANA_REGEN_SHORT = 0.2, ITEM_MOD_SPIRIT_SHORT = 0.3 },
        ["Feral"] = { ITEM_MOD_STR_SHORT = 2.15, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_AGILITY_SHORT = 2.25, ITEM_MOD_HIT_RATING_SHORT = 2.0, ITEM_MOD_CRIT_RATING_SHORT = 1.6, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.2, ITEM_MOD_FERAL_ATTACK_POWER_SHORT = 1.0 },
        ["Restoration"] = { ITEM_MOD_INTELLECT_SHORT = 1.0, ITEM_MOD_SPELL_POWER_SHORT = 1.0, ITEM_MOD_SPELL_DAMAGE_DONE_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_MANA_REGEN_SHORT = 0.6, ITEM_MOD_SPIRIT_SHORT = 0.7 },
        ["Specs"] = { "Balance", "Feral", "Restoration" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["ROGUE"] = {
        ["Assassination"] = { ITEM_MOD_AGILITY_SHORT = 2.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.9, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.0, ITEM_MOD_ATTACK_POWER_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Combat"] = { ITEM_MOD_AGILITY_SHORT = 1.9, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.8, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Subtlety"] = { ITEM_MOD_AGILITY_SHORT = 1.8, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 2.0, ITEM_MOD_CRIT_RATING_SHORT = 1.4, ITEM_MOD_HASTE_RATING_SHORT = 1.2, ITEM_MOD_HIT_RATING_SHORT = 1.0, ITEM_MOD_ATTACK_POWER_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.7, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Specs"] = { "Assassination", "Combat", "Subtlety" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE, ["ExpCap"] = 214
    },
    ["HUNTER"] = {
        ["Beast Mastery"] = { ITEM_MOD_AGILITY_SHORT = 2.0, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.7, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 0.8, ITEM_MOD_HIT_RATING_SHORT = 1.1, ITEM_MOD_ATTACK_POWER_SHORT = 0.8, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_INTELLECT_SHORT = 0.0 },
        ["Marksmanship"] = { ITEM_MOD_AGILITY_SHORT = 1.9, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.6, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_ATTACK_POWER_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_INTELLECT_SHORT = 0.0 },
        ["Survival"] = { ITEM_MOD_AGILITY_SHORT = 1.9, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.7, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.0, ITEM_MOD_ATTACK_POWER_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Specs"] = { "Beast Mastery", "Marksmanship", "Survival" }, ["HitCap"] = 263, ["HitRatingType"] = CR_HIT_MELEE
    },
    ["SHAMAN"] = {
        ["Elemental"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.5, ITEM_MOD_INTELLECT_SHORT = 1.4, ITEM_MOD_HIT_RATING_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Enhancement"] = { ITEM_MOD_AGILITY_SHORT = 1.8, ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 1.8, ITEM_MOD_CRIT_RATING_SHORT = 1.3, ITEM_MOD_HASTE_RATING_SHORT = 1.1, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_ATTACK_POWER_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.75, ITEM_MOD_EXPERTISE_RATING_SHORT = 0.0 },
        ["Restoration"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.3, ITEM_MOD_INTELLECT_SHORT = 1.5, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_SPIRIT_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8 },
        ["Specs"] = { "Elemental", "Enhancement", "Restoration" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
    ["WARLOCK"] = {
        ["Affliction"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.5, ITEM_MOD_INTELLECT_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.2, ITEM_MOD_CRIT_RATING_SHORT = 0.9, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_SPIRIT_SHORT = 0.0, ITEM_MOD_MANA_REGEN_SHORT = 0.0 },
        ["Demonology"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.4, ITEM_MOD_INTELLECT_SHORT = 1.3, ITEM_MOD_HIT_RATING_SHORT = 1.1, ITEM_MOD_CRIT_RATING_SHORT = 1.0, ITEM_MOD_HASTE_RATING_SHORT = 0.9, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_SPIRIT_SHORT = 0.0, ITEM_MOD_MANA_REGEN_SHORT = 0.0 },
        ["Destruction"] = { ITEM_MOD_SPELL_POWER_SHORT = 1.5, ITEM_MOD_INTELLECT_SHORT = 1.3, ITEM_MOD_CRIT_RATING_SHORT = 1.2, ITEM_MOD_HIT_RATING_SHORT = 1.1, ITEM_MOD_HASTE_RATING_SHORT = 1.0, ITEM_MOD_STAMINA_SHORT = 0.8, ITEM_MOD_SPIRIT_SHORT = 0.0, ITEM_MOD_MANA_REGEN_SHORT = 0.0 },
        ["Specs"] = { "Affliction", "Demonology", "Destruction" }, ["HitCap"] = 446, ["HitRatingType"] = CR_HIT_SPELL
    },
}

-- =============================================================================
-- Enchant stat data — WotLK 3.3.5a Phase 5
-- Maps permanent enchantID (from item link field 2) to stat tables.
-- =============================================================================
local enchantData = {
    -- Head (Arcanum)
    [3817] = { ITEM_MOD_ATTACK_POWER_SHORT = 50, ITEM_MOD_CRIT_RATING_SHORT = 20 },
    [3818] = { ITEM_MOD_STAMINA_SHORT = 37, ITEM_MOD_DEFENSE_RATING_SHORT = 20 },
    [3819] = { ITEM_MOD_SPELL_POWER_SHORT = 30, ITEM_MOD_MANA_REGEN_SHORT = 10 },
    [3820] = { ITEM_MOD_SPELL_POWER_SHORT = 30, ITEM_MOD_CRIT_RATING_SHORT = 20 },
    -- Shoulders
    [3808] = { ITEM_MOD_ATTACK_POWER_SHORT = 40, ITEM_MOD_CRIT_RATING_SHORT = 15 },
    [3809] = { ITEM_MOD_SPELL_POWER_SHORT = 24, ITEM_MOD_MANA_REGEN_SHORT = 8 },
    [3810] = { ITEM_MOD_SPELL_POWER_SHORT = 24, ITEM_MOD_CRIT_RATING_SHORT = 15 },
    [3811] = { ITEM_MOD_DODGE_RATING_SHORT = 20, ITEM_MOD_DEFENSE_RATING_SHORT = 15 },
    [3835] = { ITEM_MOD_ATTACK_POWER_SHORT = 120, ITEM_MOD_CRIT_RATING_SHORT = 15 },
    [3836] = { ITEM_MOD_SPELL_POWER_SHORT = 70, ITEM_MOD_CRIT_RATING_SHORT = 15 },
    [3837] = { ITEM_MOD_SPELL_POWER_SHORT = 70, ITEM_MOD_MANA_REGEN_SHORT = 8 },
    [3838] = { ITEM_MOD_DODGE_RATING_SHORT = 60, ITEM_MOD_DEFENSE_RATING_SHORT = 15 },
    [3793] = { ITEM_MOD_ATTACK_POWER_SHORT = 30, ITEM_MOD_CRIT_RATING_SHORT = 10 },
    [3794] = { ITEM_MOD_SPELL_POWER_SHORT = 18, ITEM_MOD_CRIT_RATING_SHORT = 10 },
    [3795] = { ITEM_MOD_SPELL_POWER_SHORT = 18, ITEM_MOD_MANA_REGEN_SHORT = 5 },
    [3852] = { ITEM_MOD_STAMINA_SHORT = 30 },
    -- Cloak
    [3722] = { ITEM_MOD_AGILITY_SHORT = 22 },
    [3243] = { ITEM_MOD_HASTE_RATING_SHORT = 23 },
    [1099] = { ITEM_MOD_DEFENSE_RATING_SHORT = 16 },
    [3831] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },
    -- Chest
    [3832] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 10, ITEM_MOD_INTELLECT_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },
    [2381] = { ITEM_MOD_STR_SHORT = 6, ITEM_MOD_AGILITY_SHORT = 6, ITEM_MOD_STAMINA_SHORT = 6, ITEM_MOD_INTELLECT_SHORT = 6, ITEM_MOD_SPIRIT_SHORT = 6 },
    [1953] = { ITEM_MOD_DEFENSE_RATING_SHORT = 22 },
    -- Wrist
    [3850] = { ITEM_MOD_SPELL_POWER_SHORT = 30 },
    [3845] = { ITEM_MOD_ATTACK_POWER_SHORT = 50 },
    [3757] = { ITEM_MOD_STAMINA_SHORT = 40 },
    [2332] = { ITEM_MOD_SPELL_POWER_SHORT = 23 },
    [3758] = { ITEM_MOD_INTELLECT_SHORT = 16 },
    [3756] = { ITEM_MOD_SPIRIT_SHORT = 18 },
    [2661] = { ITEM_MOD_STR_SHORT = 12 },
    [1600] = { ITEM_MOD_ATTACK_POWER_SHORT = 38 },
    [3231] = { ITEM_MOD_ATTACK_POWER_SHORT = 130 },
    [3234] = { ITEM_MOD_SPELL_POWER_SHORT = 76 },
    [3763] = { ITEM_MOD_STAMINA_SHORT = 102 },
    -- Hands
    [3246] = { ITEM_MOD_ATTACK_POWER_SHORT = 44 },
    [3249] = { ITEM_MOD_SPELL_POWER_SHORT = 28 },
    [3253] = { ITEM_MOD_AGILITY_SHORT = 20 },
    [3222] = { ITEM_MOD_HIT_RATING_SHORT = 20 },
    [3829] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 15 },
    -- Legs
    [3822] = { ITEM_MOD_ATTACK_POWER_SHORT = 75, ITEM_MOD_CRIT_RATING_SHORT = 22 },
    [3823] = { ITEM_MOD_STAMINA_SHORT = 55, ITEM_MOD_AGILITY_SHORT = 22 },
    [3325] = { ITEM_MOD_ATTACK_POWER_SHORT = 55, ITEM_MOD_CRIT_RATING_SHORT = 15 },
    [3326] = { ITEM_MOD_STAMINA_SHORT = 40, ITEM_MOD_AGILITY_SHORT = 12 },
    [3719] = { ITEM_MOD_SPELL_POWER_SHORT = 50, ITEM_MOD_SPIRIT_SHORT = 20 },
    [3721] = { ITEM_MOD_SPELL_POWER_SHORT = 50, ITEM_MOD_STAMINA_SHORT = 30 },
    [3720] = { ITEM_MOD_SPELL_POWER_SHORT = 35, ITEM_MOD_SPIRIT_SHORT = 20 },
    [3718] = { ITEM_MOD_SPELL_POWER_SHORT = 35, ITEM_MOD_STAMINA_SHORT = 20 },
    -- Feet
    [3232] = { ITEM_MOD_STAMINA_SHORT = 15 },
    [1075] = { ITEM_MOD_AGILITY_SHORT = 12 },
    [3824] = { ITEM_MOD_ATTACK_POWER_SHORT = 32 },
    [1147] = { ITEM_MOD_STAMINA_SHORT = 22 },
    -- Weapon
    [3834] = { ITEM_MOD_HIT_RATING_SHORT = 25, ITEM_MOD_CRIT_RATING_SHORT = 25 },
    [3830] = { ITEM_MOD_SPELL_POWER_SHORT = 63 },
    [3844] = { ITEM_MOD_SPIRIT_SHORT = 45 },
    [3225] = { ITEM_MOD_AGILITY_SHORT = 26 },
    [2673] = { ITEM_MOD_SPELL_POWER_SHORT = 40 },
    -- 2H Weapon
    [3827] = { ITEM_MOD_ATTACK_POWER_SHORT = 110 },
    [3828] = { ITEM_MOD_ATTACK_POWER_SHORT = 85 },
    -- Shield
    [1952] = { ITEM_MOD_DEFENSE_RATING_SHORT = 20 },
    [1071] = { ITEM_MOD_INTELLECT_SHORT = 25 },
    [3849] = { ITEM_MOD_BLOCK_VALUE_SHORT = 40 },
    -- Ranged
    [3843] = { ITEM_MOD_CRIT_RATING_SHORT = 40 },
    [3608] = { ITEM_MOD_HIT_RATING_SHORT = 40 },
    -- Ring (Enchanting)
    [3839] = { ITEM_MOD_ATTACK_POWER_SHORT = 40 },
    [3840] = { ITEM_MOD_SPELL_POWER_SHORT = 23 },
    [3791] = { ITEM_MOD_STAMINA_SHORT = 30 },
}

-- Static gem data: maps item IDs to stat tables.
-- GetItemStats(gemLink) returns empty tables for gems in WotLK 3.3.5a,
-- so this table provides the fallback.  All IDs verified via Wowhead.
local gemData = {
    -- ===== EPIC GEMS (Phase 3+) =====

    -- Cardinal Ruby (Red)
    [40111] = { ITEM_MOD_STR_SHORT = 20 },                                                        -- Bold
    [40112] = { ITEM_MOD_AGILITY_SHORT = 20 },                                                    -- Delicate
    [40113] = { ITEM_MOD_SPELL_POWER_SHORT = 23 },                                                -- Runed
    [40114] = { ITEM_MOD_ATTACK_POWER_SHORT = 40 },                                               -- Bright
    [40115] = { ITEM_MOD_DODGE_RATING_SHORT = 20 },                                               -- Subtle
    [40116] = { ITEM_MOD_PARRY_RATING_SHORT = 20 },                                               -- Flashing
    [40117] = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 20 },                                   -- Fractured
    [40118] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 20 },                                           -- Precise

    -- King's Amber (Yellow)
    [40119] = { ITEM_MOD_DEFENSE_RATING_SHORT = 20 },                                             -- Thick
    [40120] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 20 },                                          -- Mystic
    [40124] = { ITEM_MOD_CRIT_RATING_SHORT = 20 },                                                -- Smooth
    [40125] = { ITEM_MOD_HIT_RATING_SHORT = 20 },                                                 -- Rigid
    [40128] = { ITEM_MOD_HASTE_RATING_SHORT = 20 },                                               -- Quick

    -- Majestic Zircon (Blue)
    [40121] = { ITEM_MOD_STAMINA_SHORT = 30 },                                                    -- Solid
    [40122] = { ITEM_MOD_SPIRIT_SHORT = 20 },                                                     -- Sparkling
    [40123] = { ITEM_MOD_MANA_REGEN_SHORT = 10 },                                                 -- Lustrous
    [40126] = { ITEM_MOD_SPELL_PENETRATION_SHORT = 20 },                                          -- Stormy

    -- Ametrine (Orange — Red/Yellow)
    [40142] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_CRIT_RATING_SHORT = 10 },                       -- Inscribed
    [40143] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_HIT_RATING_SHORT = 10 },                        -- Etched
    [40144] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_DEFENSE_RATING_SHORT = 10 },                    -- Champion's
    [40145] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_RESILIENCE_RATING_SHORT = 10 },                 -- Resplendent
    [40146] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_HASTE_RATING_SHORT = 10 },                      -- Fierce
    [40147] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_CRIT_RATING_SHORT = 10 },                   -- Deadly
    [40148] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_HIT_RATING_SHORT = 10 },                    -- Glinting
    [40149] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_RESILIENCE_RATING_SHORT = 10 },             -- Lucent
    [40150] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_HASTE_RATING_SHORT = 10 },                  -- Deft
    [40151] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_INTELLECT_SHORT = 10 },                 -- Luminous
    [40152] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_CRIT_RATING_SHORT = 10 },               -- Potent
    [40153] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_HIT_RATING_SHORT = 10 },                -- Veiled
    [40154] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_RESILIENCE_RATING_SHORT = 10 },         -- Durable
    [40155] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_HASTE_RATING_SHORT = 10 },              -- Reckless
    [40156] = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_CRIT_RATING_SHORT = 10 },              -- Wicked
    [40157] = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_HIT_RATING_SHORT = 10 },               -- Pristine
    [40158] = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_RESILIENCE_RATING_SHORT = 10 },        -- Empowered
    [40159] = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_HASTE_RATING_SHORT = 10 },             -- Stark
    [40160] = { ITEM_MOD_DODGE_RATING_SHORT = 10, ITEM_MOD_DEFENSE_RATING_SHORT = 10 },           -- Stalwart
    [40161] = { ITEM_MOD_PARRY_RATING_SHORT = 10, ITEM_MOD_DEFENSE_RATING_SHORT = 10 },           -- Glimmering
    [40162] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 10, ITEM_MOD_HIT_RATING_SHORT = 10 },           -- Accurate

    -- Dreadstone (Purple — Red/Blue)
    [40129] = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                           -- Sovereign
    [40130] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                       -- Shifting
    [40131] = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_MANA_REGEN_SHORT = 5 },                     -- Tenuous
    [40132] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_STAMINA_SHORT = 15 },                   -- Glowing
    [40133] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_SPIRIT_SHORT = 10 },                    -- Purified
    [40134] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_MANA_REGEN_SHORT = 5 },                 -- Royal
    [40135] = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_SPELL_PENETRATION_SHORT = 13 },         -- Mysterious
    [40136] = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_STAMINA_SHORT = 15 },                  -- Balanced
    [40137] = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_MANA_REGEN_SHORT = 5 },                -- Infused
    [40138] = { ITEM_MOD_DODGE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                  -- Regal
    [40139] = { ITEM_MOD_PARRY_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                  -- Defender's
    [40140] = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },      -- Puissant
    [40141] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },              -- Guardian's

    -- Eye of Zul (Green — Yellow/Blue)
    [40165] = { ITEM_MOD_CRIT_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                   -- Jagged
    [40166] = { ITEM_MOD_HIT_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                    -- Vivid
    [40167] = { ITEM_MOD_DEFENSE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                -- Enduring
    [40168] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },             -- Steady
    [40169] = { ITEM_MOD_HASTE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                  -- Forceful
    [40170] = { ITEM_MOD_INTELLECT_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },                      -- Seer's
    [40171] = { ITEM_MOD_CRIT_RATING_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },                    -- Misty
    [40172] = { ITEM_MOD_HIT_RATING_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },                     -- Shining
    [40173] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },              -- Turbid
    [40174] = { ITEM_MOD_HASTE_RATING_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },                   -- Intricate
    [40175] = { ITEM_MOD_INTELLECT_SHORT = 10, ITEM_MOD_MANA_REGEN_SHORT = 5 },                   -- Dazzling
    [40176] = { ITEM_MOD_CRIT_RATING_SHORT = 10, ITEM_MOD_MANA_REGEN_SHORT = 5 },                 -- Sundered
    [40177] = { ITEM_MOD_HIT_RATING_SHORT = 10, ITEM_MOD_MANA_REGEN_SHORT = 5 },                  -- Lambent
    [40178] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 10, ITEM_MOD_MANA_REGEN_SHORT = 5 },           -- Opaque
    [40179] = { ITEM_MOD_HASTE_RATING_SHORT = 10, ITEM_MOD_MANA_REGEN_SHORT = 5 },                -- Energized
    [40180] = { ITEM_MOD_CRIT_RATING_SHORT = 10, ITEM_MOD_SPELL_PENETRATION_SHORT = 13 },         -- Radiant
    [40181] = { ITEM_MOD_HIT_RATING_SHORT = 10, ITEM_MOD_SPELL_PENETRATION_SHORT = 13 },          -- Tense
    [40182] = { ITEM_MOD_HASTE_RATING_SHORT = 10, ITEM_MOD_SPELL_PENETRATION_SHORT = 13 },        -- Shattered

    -- ===== DRAGON'S EYE (JC-only, Phase 1+) =====

    -- Red Dragon's Eye
    [42142] = { ITEM_MOD_STR_SHORT = 34 },                                                        -- Bold
    [42143] = { ITEM_MOD_AGILITY_SHORT = 34 },                                                    -- Delicate
    [42144] = { ITEM_MOD_SPELL_POWER_SHORT = 39 },                                                -- Runed
    [42151] = { ITEM_MOD_DODGE_RATING_SHORT = 34 },                                               -- Subtle
    [42152] = { ITEM_MOD_PARRY_RATING_SHORT = 34 },                                               -- Flashing
    [42153] = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 34 },                                   -- Fractured
    [42154] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 34 },                                           -- Precise

    -- Yellow Dragon's Eye
    [42148] = { ITEM_MOD_INTELLECT_SHORT = 34 },                                                  -- Brilliant
    [42149] = { ITEM_MOD_CRIT_RATING_SHORT = 34 },                                                -- Smooth
    [42150] = { ITEM_MOD_HASTE_RATING_SHORT = 34 },                                               -- Quick
    [42156] = { ITEM_MOD_HIT_RATING_SHORT = 34 },                                                 -- Rigid
    [42157] = { ITEM_MOD_DEFENSE_RATING_SHORT = 34 },                                             -- Thick
    [42158] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 34 },                                          -- Mystic

    -- Blue Dragon's Eye
    [36766] = { ITEM_MOD_ATTACK_POWER_SHORT = 68 },                                               -- Bright
    [36767] = { ITEM_MOD_STAMINA_SHORT = 51 },                                                    -- Solid
    [42145] = { ITEM_MOD_SPIRIT_SHORT = 34 },                                                     -- Sparkling
    [42146] = { ITEM_MOD_MANA_REGEN_SHORT = 17 },                                                 -- Lustrous
    [42155] = { ITEM_MOD_SPELL_PENETRATION_SHORT = 43 },                                          -- Stormy

    -- ===== RARE GEMS (Phase 1+) =====

    -- Scarlet Ruby (Red)
    [39996] = { ITEM_MOD_STR_SHORT = 16 },                                                        -- Bold
    [39997] = { ITEM_MOD_AGILITY_SHORT = 16 },                                                    -- Delicate
    [39998] = { ITEM_MOD_SPELL_POWER_SHORT = 19 },                                                -- Runed
    [39999] = { ITEM_MOD_ATTACK_POWER_SHORT = 32 },                                               -- Bright
    [40000] = { ITEM_MOD_DODGE_RATING_SHORT = 16 },                                               -- Subtle
    [40001] = { ITEM_MOD_PARRY_RATING_SHORT = 16 },                                               -- Flashing
    [40002] = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 16 },                                   -- Fractured
    [40003] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 16 },                                           -- Precise

    -- Autumn's Glow (Yellow)
    [40013] = { ITEM_MOD_CRIT_RATING_SHORT = 16 },                                                -- Smooth
    [40014] = { ITEM_MOD_DEFENSE_RATING_SHORT = 16 },                                             -- Thick
    [40015] = { ITEM_MOD_HIT_RATING_SHORT = 16 },                                                 -- Rigid
    [40016] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 16 },                                          -- Mystic
    [40017] = { ITEM_MOD_HASTE_RATING_SHORT = 16 },                                               -- Quick

    -- Sky Sapphire (Blue)
    [40008] = { ITEM_MOD_STAMINA_SHORT = 24 },                                                    -- Solid
    [40009] = { ITEM_MOD_SPIRIT_SHORT = 16 },                                                     -- Sparkling
    [40010] = { ITEM_MOD_MANA_REGEN_SHORT = 8 },                                                  -- Lustrous
    [40011] = { ITEM_MOD_SPELL_PENETRATION_SHORT = 16 },                                          -- Stormy

    -- Monarch Topaz (Orange — Red/Yellow)
    [40037] = { ITEM_MOD_STR_SHORT = 8, ITEM_MOD_CRIT_RATING_SHORT = 8 },                         -- Inscribed
    [40038] = { ITEM_MOD_STR_SHORT = 8, ITEM_MOD_HIT_RATING_SHORT = 8 },                          -- Etched
    [40039] = { ITEM_MOD_STR_SHORT = 8, ITEM_MOD_DEFENSE_RATING_SHORT = 8 },                      -- Champion's
    [40040] = { ITEM_MOD_STR_SHORT = 8, ITEM_MOD_RESILIENCE_RATING_SHORT = 8 },                   -- Resplendent
    [40041] = { ITEM_MOD_STR_SHORT = 8, ITEM_MOD_HASTE_RATING_SHORT = 8 },                        -- Fierce
    [40042] = { ITEM_MOD_AGILITY_SHORT = 8, ITEM_MOD_CRIT_RATING_SHORT = 8 },                     -- Deadly
    [40043] = { ITEM_MOD_AGILITY_SHORT = 8, ITEM_MOD_HIT_RATING_SHORT = 8 },                      -- Glinting
    [40044] = { ITEM_MOD_AGILITY_SHORT = 8, ITEM_MOD_RESILIENCE_RATING_SHORT = 8 },               -- Lucent
    [40045] = { ITEM_MOD_AGILITY_SHORT = 8, ITEM_MOD_HASTE_RATING_SHORT = 8 },                    -- Deft
    [40046] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_INTELLECT_SHORT = 8 },                   -- Luminous
    [40047] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_CRIT_RATING_SHORT = 8 },                 -- Potent
    [40048] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_HIT_RATING_SHORT = 8 },                  -- Veiled
    [40049] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_RESILIENCE_RATING_SHORT = 8 },           -- Durable
    [40050] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_HASTE_RATING_SHORT = 8 },                -- Reckless
    [40051] = { ITEM_MOD_ATTACK_POWER_SHORT = 16, ITEM_MOD_CRIT_RATING_SHORT = 8 },               -- Wicked
    [40052] = { ITEM_MOD_ATTACK_POWER_SHORT = 16, ITEM_MOD_HIT_RATING_SHORT = 8 },                -- Pristine
    [40053] = { ITEM_MOD_ATTACK_POWER_SHORT = 16, ITEM_MOD_RESILIENCE_RATING_SHORT = 8 },         -- Empowered
    [40054] = { ITEM_MOD_ATTACK_POWER_SHORT = 16, ITEM_MOD_HASTE_RATING_SHORT = 8 },              -- Stark
    [40055] = { ITEM_MOD_DODGE_RATING_SHORT = 8, ITEM_MOD_DEFENSE_RATING_SHORT = 8 },             -- Stalwart
    [40056] = { ITEM_MOD_PARRY_RATING_SHORT = 8, ITEM_MOD_DEFENSE_RATING_SHORT = 8 },             -- Glimmering
    [40057] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 8, ITEM_MOD_HIT_RATING_SHORT = 8 },             -- Accurate

    -- Twilight Opal (Purple — Red/Blue)
    [40022] = { ITEM_MOD_STR_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                            -- Sovereign
    [40023] = { ITEM_MOD_AGILITY_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                        -- Shifting
    [40024] = { ITEM_MOD_AGILITY_SHORT = 8, ITEM_MOD_MANA_REGEN_SHORT = 4 },                      -- Tenuous
    [40025] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_STAMINA_SHORT = 12 },                    -- Glowing
    [40026] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_SPIRIT_SHORT = 8 },                      -- Purified
    [40027] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_MANA_REGEN_SHORT = 4 },                  -- Royal
    [40028] = { ITEM_MOD_SPELL_POWER_SHORT = 9, ITEM_MOD_SPELL_PENETRATION_SHORT = 10 },          -- Mysterious
    [40029] = { ITEM_MOD_ATTACK_POWER_SHORT = 16, ITEM_MOD_STAMINA_SHORT = 12 },                  -- Balanced
    [40030] = { ITEM_MOD_ATTACK_POWER_SHORT = 16, ITEM_MOD_MANA_REGEN_SHORT = 4 },                -- Infused
    [40031] = { ITEM_MOD_DODGE_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                   -- Regal
    [40032] = { ITEM_MOD_PARRY_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                   -- Defender's
    [40033] = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },       -- Puissant
    [40034] = { ITEM_MOD_EXPERTISE_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },               -- Guardian's

    -- Forest Emerald (Green — Yellow/Blue)
    [40058] = { ITEM_MOD_CRIT_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                    -- Jagged
    [40059] = { ITEM_MOD_HIT_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                     -- Vivid
    [40060] = { ITEM_MOD_DEFENSE_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                 -- Enduring
    [40061] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },              -- Steady
    [40062] = { ITEM_MOD_HASTE_RATING_SHORT = 8, ITEM_MOD_STAMINA_SHORT = 12 },                   -- Forceful
    [40063] = { ITEM_MOD_INTELLECT_SHORT = 8, ITEM_MOD_SPIRIT_SHORT = 8 },                        -- Seer's
    [40064] = { ITEM_MOD_CRIT_RATING_SHORT = 8, ITEM_MOD_SPIRIT_SHORT = 8 },                      -- Misty
    [40065] = { ITEM_MOD_HIT_RATING_SHORT = 8, ITEM_MOD_SPIRIT_SHORT = 8 },                       -- Shining
    [40066] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 8, ITEM_MOD_SPIRIT_SHORT = 8 },                -- Turbid
    [40067] = { ITEM_MOD_HASTE_RATING_SHORT = 8, ITEM_MOD_SPIRIT_SHORT = 8 },                     -- Intricate
    [40068] = { ITEM_MOD_INTELLECT_SHORT = 8, ITEM_MOD_MANA_REGEN_SHORT = 4 },                    -- Dazzling
    [40069] = { ITEM_MOD_CRIT_RATING_SHORT = 8, ITEM_MOD_MANA_REGEN_SHORT = 4 },                  -- Sundered
    [40070] = { ITEM_MOD_HIT_RATING_SHORT = 8, ITEM_MOD_MANA_REGEN_SHORT = 4 },                   -- Lambent
    [40071] = { ITEM_MOD_RESILIENCE_RATING_SHORT = 8, ITEM_MOD_MANA_REGEN_SHORT = 4 },            -- Opaque
    [40072] = { ITEM_MOD_HASTE_RATING_SHORT = 8, ITEM_MOD_MANA_REGEN_SHORT = 4 },                 -- Energized
    [40073] = { ITEM_MOD_CRIT_RATING_SHORT = 8, ITEM_MOD_SPELL_PENETRATION_SHORT = 10 },          -- Radiant
    [40074] = { ITEM_MOD_HIT_RATING_SHORT = 8, ITEM_MOD_SPELL_PENETRATION_SHORT = 10 },           -- Tense
    [40075] = { ITEM_MOD_HASTE_RATING_SHORT = 8, ITEM_MOD_SPELL_PENETRATION_SHORT = 10 },         -- Shattered
}

-- =============================================================================
-- Trinket proc/on-use fallback data
-- Pre-computed passive-equivalent stats for trinkets with proc or on-use effects.
-- These values are ADDITIVE to any passive stats already returned by GetItemStats().
-- Formula: proc trinkets = stat_amount * buff_duration / ICD
--          on-use trinkets = stat_amount * active_duration / cooldown
-- =============================================================================
local trinketProcData = {
    -- Melee/Physical DPS Trinkets
    [50363] = { ITEM_MOD_AGILITY_SHORT = 171 },                                                   -- Deathbringer's Will (Normal) — avg across random procs
    [50362] = { ITEM_MOD_AGILITY_SHORT = 200 },                                                   -- Deathbringer's Will (Heroic)
    [50198] = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 151 },                                  -- Needle-Encrusted Scorpion — 678 ArP, 10s/45s
    [47303] = { ITEM_MOD_AGILITY_SHORT = 170 },                                                   -- Death's Choice (Normal) — 510 AGI/STR, 15s/45s
    [47464] = { ITEM_MOD_AGILITY_SHORT = 170 },                                                   -- Death's Choice (Heroic)
    [50343] = { ITEM_MOD_ATTACK_POWER_SHORT = 133 },                                              -- Whispering Fanged Skull (Normal) — 400 AP, 15s/45s
    [50346] = { ITEM_MOD_ATTACK_POWER_SHORT = 133 },                                              -- Whispering Fanged Skull (Heroic)
    [54569] = { ITEM_MOD_ATTACK_POWER_SHORT = 287 },                                              -- Sharpened Twilight Scale (Normal) — 861 AP, 15s/45s
    [54590] = { ITEM_MOD_ATTACK_POWER_SHORT = 435 },                                              -- Sharpened Twilight Scale (Heroic) — 1304 AP, 15s/45s
    -- Caster DPS Trinkets
    [50348] = { ITEM_MOD_SPELL_POWER_SHORT = 234 },                                               -- Dislodged Foreign Object (Normal) — stacking SP, conservative avg
    [50353] = { ITEM_MOD_SPELL_POWER_SHORT = 269 },                                               -- Dislodged Foreign Object (Heroic)
    [50365] = { ITEM_MOD_SPELL_POWER_SHORT = 215 },                                               -- Phylactery of the Nameless Lich (Normal) — 1074 SP, 20s/100s
    [50360] = { ITEM_MOD_SPELL_POWER_SHORT = 241 },                                               -- Phylactery of the Nameless Lich (Heroic) — 1207 SP, 20s/100s
    [54588] = { ITEM_MOD_SPELL_POWER_SHORT = 254 },                                               -- Charred Twilight Scale (Normal) — 763 SP, 15s/45s
    [54572] = { ITEM_MOD_SPELL_POWER_SHORT = 386 },                                               -- Charred Twilight Scale (Heroic) — 1157 SP, 15s/45s
    -- Healer Trinkets
    [50359] = { ITEM_MOD_SPELL_POWER_SHORT = 100 },                                               -- Althor's Abacus (Normal) — heal proc, ~100 SP equiv
    [50366] = { ITEM_MOD_SPELL_POWER_SHORT = 115 },                                               -- Althor's Abacus (Heroic) — heal proc, ~115 SP equiv
    -- Tank Trinkets
    [50364] = { ITEM_MOD_DODGE_RATING_SHORT = 40 },                                               -- Sindragosa's Flawless Fang (Normal) — 239 dodge, 10s/60s
    [50361] = { ITEM_MOD_DODGE_RATING_SHORT = 45 },                                               -- Sindragosa's Flawless Fang (Heroic) — 268 dodge, 10s/60s
    [50356] = { RES_ARMOR = 950 },                                                                -- Corpse Tongue Coin (Normal) — 5700 armor, 20s/120s (passive dodge separate)
    [50352] = { RES_ARMOR = 1067 },                                                               -- Corpse Tongue Coin (Heroic) — 6400 armor, 20s/120s
}

local reportedUnknownEnchants = {}

function addon.GetEnchantStats(link)
    if not link then return nil end
    local enchantID = tonumber(link:match("item:%d+:(%d+)"))
    if not enchantID or enchantID == 0 then return nil end
    local data = enchantData[enchantID]
    if not data and not reportedUnknownEnchants[enchantID] then
        reportedUnknownEnchants[enchantID] = true
    end
    return data
end

function addon.GetGemStats(gemLink)
    if not gemLink then return nil end
    local gemID = tonumber(gemLink:match("item:(%d+)"))
    if not gemID then return nil end
    return gemData[gemID]
end

function addon.GetItemStatsWithEnchantAndGems(link)
    if not link then return nil end
    local stats = GetItemStats(link)
    if not stats then return nil end

    local merged = {}
    for k, v in pairs(stats) do
        merged[k] = v
    end

    -- Merge enchant stats
    local enchantStats = addon.GetEnchantStats(link)
    if enchantStats then
        for k, v in pairs(enchantStats) do
            merged[k] = (merged[k] or 0) + v
        end
    end

    -- Merge gem stats
    if GetItemGem then
        for i = 1, 3 do
            local gemName, gemLink = GetItemGem(link, i)
            if gemLink then
                local gemStats = GetItemStats(gemLink)
                if not gemStats or not next(gemStats) then
                    gemStats = addon.GetGemStats(gemLink)
                end
                if gemStats then
                    for k, v in pairs(gemStats) do
                        merged[k] = (merged[k] or 0) + v
                    end
                end
            end
        end
    end

    return merged
end

-- Gem recommendation data
local gemRecommendations = {
    ["PhysicalDPS"] = {
        bis    = { name = { enUS = "Fractured Cardinal Ruby", deDE = "Frakturierter Kardinalrubin" }, ep_stat = "ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT", ep_amount = 20 },
        budget = { name = { enUS = "Fractured Scarlet Ruby",  deDE = "Frakturierter Scharlachrubin" }, ep_stat = "ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT", ep_amount = 16 },
    },
    ["SpellDPS"] = {
        bis    = { name = { enUS = "Runed Cardinal Ruby",     deDE = "Runenverzierter Kardinalrubin" }, ep_stat = "ITEM_MOD_SPELL_POWER_SHORT", ep_amount = 23 },
        budget = { name = { enUS = "Runed Scarlet Ruby",      deDE = "Runenverzierter Scharlachrubin" }, ep_stat = "ITEM_MOD_SPELL_POWER_SHORT", ep_amount = 19 },
    },
    ["Healer"] = {
        bis    = { name = { enUS = "Runed Cardinal Ruby",     deDE = "Runenverzierter Kardinalrubin" }, ep_stat = "ITEM_MOD_SPELL_POWER_SHORT", ep_amount = 23 },
        budget = { name = { enUS = "Runed Scarlet Ruby",      deDE = "Runenverzierter Scharlachrubin" }, ep_stat = "ITEM_MOD_SPELL_POWER_SHORT", ep_amount = 19 },
    },
    ["Tank"] = {
        bis    = { name = { enUS = "Solid Majestic Zircon",   deDE = "Gediegener Majestätischer Zirkon" }, ep_stat = "ITEM_MOD_STAMINA_SHORT", ep_amount = 30 },
        budget = { name = { enUS = "Solid Sky Sapphire",      deDE = "Gediegener Himmelsaphir" }, ep_stat = "ITEM_MOD_STAMINA_SHORT", ep_amount = 24 },
    },
}

local specArchetypeMap = {
    ["MAGE"]        = { Arcane = "SpellDPS", Fire = "SpellDPS", Frost = "SpellDPS" },
    ["WARLOCK"]     = { Affliction = "SpellDPS", Demonology = "SpellDPS", Destruction = "SpellDPS" },
    ["PRIEST"]      = { Shadow = "SpellDPS", Discipline = "Healer", Holy = "Healer" },
    ["DRUID"]       = { Balance = "SpellDPS", Feral = "PhysicalDPS", Restoration = "Healer" },
    ["PALADIN"]     = { Holy = "Healer", Protection = "Tank", Retribution = "PhysicalDPS" },
    ["WARRIOR"]     = { Arms = "PhysicalDPS", Fury = "PhysicalDPS", Protection = "Tank" },
    ["DEATHKNIGHT"] = { Blood = "Tank", Frost = "PhysicalDPS", Unholy = "PhysicalDPS" },
    ["ROGUE"]       = { Assassination = "PhysicalDPS", Combat = "PhysicalDPS", Subtlety = "PhysicalDPS" },
    ["HUNTER"]      = { ["Beast Mastery"] = "PhysicalDPS", Marksmanship = "PhysicalDPS", Survival = "PhysicalDPS" },
    ["SHAMAN"]      = { Elemental = "SpellDPS", Enhancement = "PhysicalDPS", Restoration = "Healer" },
}

local gemCandidates = {
    bis = {
        { id = 40111, stat = "ITEM_MOD_STR_SHORT", amount = 20, name = { enUS = "Bold Cardinal Ruby", deDE = "Kühner Kardinalrubin" } },
        { id = 40112, stat = "ITEM_MOD_AGILITY_SHORT", amount = 20, name = { enUS = "Delicate Cardinal Ruby", deDE = "Behänder Kardinalrubin" } },
        { id = 40113, stat = "ITEM_MOD_SPELL_POWER_SHORT", amount = 23, name = { enUS = "Runed Cardinal Ruby", deDE = "Runenverzierter Kardinalrubin" } },
        { id = 40114, stat = "ITEM_MOD_ATTACK_POWER_SHORT", amount = 40, name = { enUS = "Bright Cardinal Ruby", deDE = "Leuchtender Kardinalrubin" } },
        { id = 40117, stat = "ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT", amount = 20, name = { enUS = "Fractured Cardinal Ruby", deDE = "Frakturierter Kardinalrubin" } },
        { id = 40124, stat = "ITEM_MOD_CRIT_RATING_SHORT", amount = 20, name = { enUS = "Smooth King's Amber", deDE = "Glatter Königsambra" } },
        { id = 40125, stat = "ITEM_MOD_HIT_RATING_SHORT", amount = 20, name = { enUS = "Rigid King's Amber", deDE = "Starrer Königsambra" } },
        { id = 40128, stat = "ITEM_MOD_HASTE_RATING_SHORT", amount = 20, name = { enUS = "Quick King's Amber", deDE = "Flinker Königsambra" } },
        { id = 40121, stat = "ITEM_MOD_STAMINA_SHORT", amount = 30, name = { enUS = "Solid Majestic Zircon", deDE = "Gediegener Majestätischer Zirkon" } },
        { id = 40115, stat = "ITEM_MOD_DODGE_RATING_SHORT", amount = 20, name = { enUS = "Subtle Cardinal Ruby", deDE = "Feinsinniger Kardinalrubin" } },
        { id = 40116, stat = "ITEM_MOD_PARRY_RATING_SHORT", amount = 20, name = { enUS = "Flashing Cardinal Ruby", deDE = "Blinkender Kardinalrubin" } },
        { id = 40118, stat = "ITEM_MOD_EXPERTISE_RATING_SHORT", amount = 20, name = { enUS = "Precise Cardinal Ruby", deDE = "Präziser Kardinalrubin" } },
        { id = 40119, stat = "ITEM_MOD_DEFENSE_RATING_SHORT", amount = 20, name = { enUS = "Thick King's Amber", deDE = "Massiver Königsambra" } },
    },
    budget = {
        { id = 39996, stat = "ITEM_MOD_STR_SHORT", amount = 16, name = { enUS = "Bold Scarlet Ruby", deDE = "Kühner Scharlachrubin" } },
        { id = 39997, stat = "ITEM_MOD_AGILITY_SHORT", amount = 16, name = { enUS = "Delicate Scarlet Ruby", deDE = "Behänder Scharlachrubin" } },
        { id = 39998, stat = "ITEM_MOD_SPELL_POWER_SHORT", amount = 19, name = { enUS = "Runed Scarlet Ruby", deDE = "Runenverzierter Scharlachrubin" } },
        { id = 39999, stat = "ITEM_MOD_ATTACK_POWER_SHORT", amount = 32, name = { enUS = "Bright Scarlet Ruby", deDE = "Leuchtender Scharlachrubin" } },
        { id = 40002, stat = "ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT", amount = 16, name = { enUS = "Fractured Scarlet Ruby", deDE = "Frakturierter Scharlachrubin" } },
        { id = 40013, stat = "ITEM_MOD_CRIT_RATING_SHORT", amount = 16, name = { enUS = "Smooth Autumn's Glow", deDE = "Glatter Herbstglanz" } },
        { id = 40015, stat = "ITEM_MOD_HIT_RATING_SHORT", amount = 16, name = { enUS = "Rigid Autumn's Glow", deDE = "Starrer Herbstglanz" } },
        { id = 40017, stat = "ITEM_MOD_HASTE_RATING_SHORT", amount = 16, name = { enUS = "Quick Autumn's Glow", deDE = "Flinker Herbstglanz" } },
        { id = 40008, stat = "ITEM_MOD_STAMINA_SHORT", amount = 24, name = { enUS = "Solid Sky Sapphire", deDE = "Gediegener Himmelsaphir" } },
        { id = 40000, stat = "ITEM_MOD_DODGE_RATING_SHORT", amount = 16, name = { enUS = "Subtle Scarlet Ruby", deDE = "Feinsinniger Scharlachrubin" } },
        { id = 40001, stat = "ITEM_MOD_PARRY_RATING_SHORT", amount = 16, name = { enUS = "Flashing Scarlet Ruby", deDE = "Blinkender Scharlachrubin" } },
        { id = 40003, stat = "ITEM_MOD_EXPERTISE_RATING_SHORT", amount = 16, name = { enUS = "Precise Scarlet Ruby", deDE = "Präziser Scharlachrubin" } },
        { id = 40014, stat = "ITEM_MOD_DEFENSE_RATING_SHORT", amount = 16, name = { enUS = "Thick Autumn's Glow", deDE = "Massiver Herbstglanz" } },
    },
}

local function ScoreGemCandidate(candidate, weights, playerStats, hitCap, expCap, hitType, softCaps)
    local stat = candidate.stat
    local amount = candidate.amount
    local weight = weights[stat]
    if not weight or weight <= 0 then return 0 end

    -- Hard cap check for hit
    if stat == "ITEM_MOD_HIT_RATING_SHORT" and hitCap > 0 then
        local curHit = playerStats["ITEM_MOD_HIT_RATING_SHORT"] or 0
        if curHit >= hitCap then return 0 end
        -- Partial: only count the portion under cap
        amount = math.min(amount, hitCap - curHit)
    end

    -- Hard cap check for expertise
    if stat == "ITEM_MOD_EXPERTISE_RATING_SHORT" and expCap > 0 then
        local curExp = playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] or 0
        if curExp >= expCap then return 0 end
        amount = math.min(amount, expCap - curExp)
    end

    -- Soft cap check (not for hit/exp which use hard caps above)
    if stat ~= "ITEM_MOD_HIT_RATING_SHORT" and stat ~= "ITEM_MOD_EXPERTISE_RATING_SHORT" then
        local soft = softCaps[stat]
        if soft and type(soft.cap) == "number" and soft.cap > 0 then
            local curVal = playerStats[stat] or 0
            if curVal >= soft.cap then
                -- Entire gem amount is above soft cap
                local mult = type(soft.multiplier) == "number" and soft.multiplier or 1
                if mult < 0 then mult = 0 end
                weight = weight * mult
            elseif curVal + amount > soft.cap then
                -- Partial: split below/above cap portions
                local belowCap = soft.cap - curVal
                local aboveCap = amount - belowCap
                local mult = type(soft.multiplier) == "number" and soft.multiplier or 1
                if mult < 0 then mult = 0 end
                return belowCap * weight + aboveCap * weight * mult
            end
        end
    end

    return amount * weight
end

local function FindBestGemCandidate(pool, weights, playerStats, hitCap, expCap, hitType, softCaps)
    local bestScore = 0
    local bestCandidate = nil
    for _, candidate in ipairs(pool) do
        local score = ScoreGemCandidate(candidate, weights, playerStats, hitCap, expCap, hitType, softCaps)
        if score > bestScore then
            bestScore = score
            bestCandidate = candidate
        end
    end
    return bestCandidate, bestScore
end

function addon.ResolveGemRecommendation()
    local currentWeights = addon.GetCurrentWeights()
    if not currentWeights or not next(currentWeights) then return nil end

    local classData = addon.GetClassData()
    local hitCap, expCap = 0, 0
    local hitType = nil
    if classData then
        hitType = classData["HitRatingType"]
        hitCap, expCap = addon.GetCurrentCapSettings()
    end
    local softCaps = addon.GetCurrentSoftCaps and addon.GetCurrentSoftCaps() or {}

    -- Build player stats snapshot
    local playerStats = {}
    for stat, _ in pairs(currentWeights) do
        playerStats[stat] = addon.GetCurrentPlayerStatValue(stat) or 0
    end
    -- Also gather hit/exp if not in weights
    if hitCap > 0 and hitType then
        playerStats["ITEM_MOD_HIT_RATING_SHORT"] = playerStats["ITEM_MOD_HIT_RATING_SHORT"] or (GetCombatRating and GetCombatRating(hitType) or 0)
    end
    if expCap > 0 then
        playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] = playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] or (GetCombatRating and GetCombatRating(CR_EXPERTISE) or 0)
    end
    -- Also gather soft-capped stats
    for stat, _ in pairs(softCaps) do
        if not playerStats[stat] then
            playerStats[stat] = addon.GetCurrentPlayerStatValue(stat) or 0
        end
    end

    -- Forward-simulation: find stable BiS
    local bisCandidate, bisScore = FindBestGemCandidate(gemCandidates.bis, currentWeights, playerStats, hitCap, expCap, hitType, softCaps)

    if bisCandidate then
        -- Forward-simulate: add gem stats and recheck
        local MAX_ITER = 3
        for iter = 1, MAX_ITER do
            local simStats = {}
            for k, v in pairs(playerStats) do simStats[k] = v end
            simStats[bisCandidate.stat] = (simStats[bisCandidate.stat] or 0) + bisCandidate.amount

            local newBest, newScore = FindBestGemCandidate(gemCandidates.bis, currentWeights, simStats, hitCap, expCap, hitType, softCaps)
            if not newBest or newBest.stat == bisCandidate.stat then
                break  -- stable
            end
            -- Winner changed. Use self-simulated tiebreak on final iteration.
            if iter == MAX_ITER then
                -- Self-simulation tiebreak: score each candidate with its own stats pre-applied
                local tbBest, tbScore = nil, 0
                for _, candidate in ipairs(gemCandidates.bis) do
                    local selfStats = {}
                    for k, v in pairs(playerStats) do selfStats[k] = v end
                    selfStats[candidate.stat] = (selfStats[candidate.stat] or 0) + candidate.amount
                    local score = ScoreGemCandidate(candidate, currentWeights, selfStats, hitCap, expCap, hitType, softCaps)
                    if score > tbScore then
                        tbScore = score
                        tbBest = candidate
                    end
                end
                if tbBest then
                    bisCandidate = tbBest
                    bisScore = tbScore
                end
            else
                bisCandidate = newBest
                bisScore = newScore
            end
        end
    end

    -- Find budget equivalent (same stat as BiS winner)
    local budgetCandidate, budgetScore = nil, 0
    if bisCandidate then
        for _, candidate in ipairs(gemCandidates.budget) do
            if candidate.stat == bisCandidate.stat then
                budgetScore = ScoreGemCandidate(candidate, currentWeights, playerStats, hitCap, expCap, hitType, softCaps)
                budgetCandidate = candidate
                break
            end
        end
    end

    if not bisCandidate then return nil end

    return {
        bis = {
            name = bisCandidate.name,
            ep_stat = bisCandidate.stat,
            ep_amount = bisCandidate.amount,
            computedEP = bisScore,
        },
        budget = budgetCandidate and {
            name = budgetCandidate.name,
            ep_stat = budgetCandidate.stat,
            ep_amount = budgetCandidate.amount,
            computedEP = budgetScore,
        } or nil,
    }
end

function addon.GetGemRecommendation(className, specName)
    -- Try dynamic cap-aware recommendation first
    local dynamic = addon.ResolveGemRecommendation()
    if dynamic then return dynamic end

    -- Fallback to static archetype recommendation
    local classMap = specArchetypeMap[className]
    if not classMap then return nil end
    local archetype = classMap[specName]
    if not archetype then return nil end
    return gemRecommendations[archetype]
end

-- Gem color compatibility: which socket colors each gem type can fill
-- Red = "r", Yellow = "y", Blue = "b"
local gemColorData = {
    -- BiS tier (epic) - Pure single-color
    -- Red gems (Cardinal Ruby)
    { id = 40111, stat = "ITEM_MOD_STR_SHORT",                      amount = 20, colors = {"r"},      name = { enUS = "Bold Cardinal Ruby", deDE = "Kühner Kardinalrubin" } },
    { id = 40112, stat = "ITEM_MOD_AGILITY_SHORT",                  amount = 20, colors = {"r"},      name = { enUS = "Delicate Cardinal Ruby", deDE = "Behänder Kardinalrubin" } },
    { id = 40113, stat = "ITEM_MOD_SPELL_POWER_SHORT",              amount = 23, colors = {"r"},      name = { enUS = "Runed Cardinal Ruby", deDE = "Runenverzierter Kardinalrubin" } },
    { id = 40114, stat = "ITEM_MOD_ATTACK_POWER_SHORT",             amount = 40, colors = {"r"},      name = { enUS = "Bright Cardinal Ruby", deDE = "Leuchtender Kardinalrubin" } },
    { id = 40117, stat = "ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT", amount = 20, colors = {"r"},      name = { enUS = "Fractured Cardinal Ruby", deDE = "Frakturierter Kardinalrubin" } },
    { id = 40118, stat = "ITEM_MOD_EXPERTISE_RATING_SHORT",         amount = 20, colors = {"r"},      name = { enUS = "Precise Cardinal Ruby", deDE = "Präziser Kardinalrubin" } },
    { id = 40115, stat = "ITEM_MOD_DODGE_RATING_SHORT",             amount = 20, colors = {"r"},      name = { enUS = "Subtle Cardinal Ruby", deDE = "Feinsinniger Kardinalrubin" } },
    { id = 40116, stat = "ITEM_MOD_PARRY_RATING_SHORT",             amount = 20, colors = {"r"},      name = { enUS = "Flashing Cardinal Ruby", deDE = "Blinkender Kardinalrubin" } },
    -- Yellow gems (King's Amber)
    { id = 40124, stat = "ITEM_MOD_CRIT_RATING_SHORT",              amount = 20, colors = {"y"},      name = { enUS = "Smooth King's Amber", deDE = "Glatter Königsambra" } },
    { id = 40125, stat = "ITEM_MOD_HIT_RATING_SHORT",               amount = 20, colors = {"y"},      name = { enUS = "Rigid King's Amber", deDE = "Starrer Königsambra" } },
    { id = 40128, stat = "ITEM_MOD_HASTE_RATING_SHORT",             amount = 20, colors = {"y"},      name = { enUS = "Quick King's Amber", deDE = "Flinker Königsambra" } },
    { id = 40119, stat = "ITEM_MOD_DEFENSE_RATING_SHORT",           amount = 20, colors = {"y"},      name = { enUS = "Thick King's Amber", deDE = "Massiver Königsambra" } },
    -- Blue gems (Majestic Zircon)
    { id = 40121, stat = "ITEM_MOD_STAMINA_SHORT",                  amount = 30, colors = {"b"},      name = { enUS = "Solid Majestic Zircon", deDE = "Gediegener Majestätischer Zirkon" } },
    { id = 40122, stat = "ITEM_MOD_SPIRIT_SHORT",                   amount = 20, colors = {"b"},      name = { enUS = "Sparkling Majestic Zircon", deDE = "Funkelnder Majestätischer Zirkon" } },
    -- Orange gems (Ametrine — matches Red + Yellow)
    { id = 40142, stats = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_CRIT_RATING_SHORT = 10 },              colors = {"r","y"}, name = { enUS = "Inscribed Ametrine", deDE = "Beschrifteter Ametrin" } },
    { id = 40143, stats = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_HIT_RATING_SHORT = 10 },               colors = {"r","y"}, name = { enUS = "Etched Ametrine", deDE = "Geätzter Ametrin" } },
    { id = 40146, stats = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_HASTE_RATING_SHORT = 10 },             colors = {"r","y"}, name = { enUS = "Fierce Ametrine", deDE = "Grimmiger Ametrin" } },
    { id = 40147, stats = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_CRIT_RATING_SHORT = 10 },          colors = {"r","y"}, name = { enUS = "Deadly Ametrine", deDE = "Tödlicher Ametrin" } },
    { id = 40148, stats = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_HIT_RATING_SHORT = 10 },           colors = {"r","y"}, name = { enUS = "Glinting Ametrine", deDE = "Gleißender Ametrin" } },
    { id = 40150, stats = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_HASTE_RATING_SHORT = 10 },         colors = {"r","y"}, name = { enUS = "Deft Ametrine", deDE = "Geschickter Ametrin" } },
    { id = 40152, stats = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_CRIT_RATING_SHORT = 10 },      colors = {"r","y"}, name = { enUS = "Potent Ametrine", deDE = "Mächtiger Ametrin" } },
    { id = 40153, stats = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_HIT_RATING_SHORT = 10 },       colors = {"r","y"}, name = { enUS = "Veiled Ametrine", deDE = "Verschleierter Ametrin" } },
    { id = 40155, stats = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_HASTE_RATING_SHORT = 10 },     colors = {"r","y"}, name = { enUS = "Reckless Ametrine", deDE = "Verwegener Ametrin" } },
    { id = 40151, stats = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_INTELLECT_SHORT = 10 },        colors = {"r","y"}, name = { enUS = "Luminous Ametrine", deDE = "Leuchtender Ametrin" } },
    { id = 40156, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_CRIT_RATING_SHORT = 10 },     colors = {"r","y"}, name = { enUS = "Wicked Ametrine", deDE = "Niederträchtiger Ametrin" } },
    { id = 40157, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_HIT_RATING_SHORT = 10 },      colors = {"r","y"}, name = { enUS = "Pristine Ametrine", deDE = "Makelloser Ametrin" } },
    { id = 40159, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_HASTE_RATING_SHORT = 10 },    colors = {"r","y"}, name = { enUS = "Stark Ametrine", deDE = "Schlichter Ametrin" } },
    { id = 40162, stats = { ITEM_MOD_EXPERTISE_RATING_SHORT = 10, ITEM_MOD_HIT_RATING_SHORT = 10 },  colors = {"r","y"}, name = { enUS = "Accurate Ametrine", deDE = "Zutreffender Ametrin" } },
    { id = 40160, stats = { ITEM_MOD_DODGE_RATING_SHORT = 10, ITEM_MOD_DEFENSE_RATING_SHORT = 10 },  colors = {"r","y"}, name = { enUS = "Stalwart Ametrine", deDE = "Standhafter Ametrin" } },
    { id = 40161, stats = { ITEM_MOD_PARRY_RATING_SHORT = 10, ITEM_MOD_DEFENSE_RATING_SHORT = 10 },  colors = {"r","y"}, name = { enUS = "Glimmering Ametrine", deDE = "Schimmernder Ametrin" } },
    -- Purple gems (Dreadstone — matches Red + Blue)
    { id = 40129, stats = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },                  colors = {"r","b"}, name = { enUS = "Sovereign Dreadstone", deDE = "Herrschaftlicher Schreckensstein" } },
    { id = 40130, stats = { ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },              colors = {"r","b"}, name = { enUS = "Shifting Dreadstone", deDE = "Wechselnder Schreckensstein" } },
    { id = 40132, stats = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_STAMINA_SHORT = 15 },          colors = {"r","b"}, name = { enUS = "Glowing Dreadstone", deDE = "Glühender Schreckensstein" } },
    { id = 40133, stats = { ITEM_MOD_SPELL_POWER_SHORT = 12, ITEM_MOD_SPIRIT_SHORT = 10 },           colors = {"r","b"}, name = { enUS = "Purified Dreadstone", deDE = "Gereinigter Schreckensstein" } },
    { id = 40136, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 20, ITEM_MOD_STAMINA_SHORT = 15 },         colors = {"r","b"}, name = { enUS = "Balanced Dreadstone", deDE = "Ausgewogener Schreckensstein" } },
    { id = 40140, stats = { ITEM_MOD_ARMOR_PENETRATION_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 }, colors = {"r","b"}, name = { enUS = "Puissant Dreadstone", deDE = "Mächtiger Schreckensstein" } },
    { id = 40141, stats = { ITEM_MOD_EXPERTISE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },     colors = {"r","b"}, name = { enUS = "Guardian's Dreadstone", deDE = "Wächter-Schreckensstein" } },
    { id = 40138, stats = { ITEM_MOD_DODGE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },         colors = {"r","b"}, name = { enUS = "Regal Dreadstone", deDE = "Stattlicher Schreckensstein" } },
    { id = 40139, stats = { ITEM_MOD_PARRY_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },         colors = {"r","b"}, name = { enUS = "Defender's Dreadstone", deDE = "Verteidiger-Schreckensstein" } },
    -- Green gems (Eye of Zul — matches Yellow + Blue)
    { id = 40165, stats = { ITEM_MOD_CRIT_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },          colors = {"y","b"}, name = { enUS = "Jagged Eye of Zul", deDE = "Gezacktes Auge von Zul" } },
    { id = 40166, stats = { ITEM_MOD_HIT_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },           colors = {"y","b"}, name = { enUS = "Vivid Eye of Zul", deDE = "Lebhaftes Auge von Zul" } },
    { id = 40169, stats = { ITEM_MOD_HASTE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },         colors = {"y","b"}, name = { enUS = "Forceful Eye of Zul", deDE = "Energisches Auge von Zul" } },
    { id = 40167, stats = { ITEM_MOD_DEFENSE_RATING_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 15 },       colors = {"y","b"}, name = { enUS = "Enduring Eye of Zul", deDE = "Beständiges Auge von Zul" } },
    { id = 40170, stats = { ITEM_MOD_INTELLECT_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 },             colors = {"y","b"}, name = { enUS = "Seer's Eye of Zul", deDE = "Seher-Auge von Zul" } },
}

local function GemMatchesSocket(gemColors, socketColor)
    for _, c in ipairs(gemColors) do
        if c == socketColor then return true end
    end
    return false
end

local function ScoreGemEntry(gem, weights, playerStats, hitCap, expCap, hitType, softCaps)
    -- Single-stat gem (has .stat and .amount)
    if gem.stat then
        return ScoreGemCandidate(gem, weights, playerStats, hitCap, expCap, hitType, softCaps)
    end
    -- Multi-stat gem (has .stats table)
    if gem.stats then
        local total = 0
        for stat, amount in pairs(gem.stats) do
            local pseudo = { stat = stat, amount = amount }
            total = total + ScoreGemCandidate(pseudo, weights, playerStats, hitCap, expCap, hitType, softCaps)
        end
        return total
    end
    return 0
end

local function FindBestGemForSocket(socketColor, weights, playerStats, hitCap, expCap, hitType, softCaps)
    local bestGem, bestScore = nil, 0
    for _, gem in ipairs(gemColorData) do
        if GemMatchesSocket(gem.colors, socketColor) then
            local score = ScoreGemEntry(gem, weights, playerStats, hitCap, expCap, hitType, softCaps)
            if score > bestScore then
                bestScore = score
                bestGem = gem
            end
        end
    end
    return bestGem, bestScore
end

function addon.ResolvePerSocketRecommendation(socketColors, bonusStat, bonusAmount)
    -- socketColors: { "r", "y", "b" } list of empty socket colors
    -- bonusStat: stat key for socket bonus (e.g., "ITEM_MOD_STR_SHORT") or nil
    -- bonusAmount: numeric amount of socket bonus or 0

    if not socketColors or #socketColors == 0 then return nil end

    local currentWeights = addon.GetCurrentWeights()
    if not currentWeights or not next(currentWeights) then return nil end

    local classData = addon.GetClassData()
    local hitCap, expCap = 0, 0
    local hitType = nil
    if classData then
        hitType = classData["HitRatingType"]
        hitCap, expCap = addon.GetCurrentCapSettings()
    end
    local softCaps = addon.GetCurrentSoftCaps and addon.GetCurrentSoftCaps() or {}

    -- Build player stats
    local playerStats = {}
    for stat, _ in pairs(currentWeights) do
        playerStats[stat] = addon.GetCurrentPlayerStatValue(stat) or 0
    end
    if hitCap > 0 and hitType then
        playerStats["ITEM_MOD_HIT_RATING_SHORT"] = playerStats["ITEM_MOD_HIT_RATING_SHORT"] or (GetCombatRating and GetCombatRating(hitType) or 0)
    end
    if expCap > 0 then
        playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] = playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] or (GetCombatRating and GetCombatRating(CR_EXPERTISE) or 0)
    end
    for stat, _ in pairs(softCaps) do
        if not playerStats[stat] then
            playerStats[stat] = addon.GetCurrentPlayerStatValue(stat) or 0
        end
    end

    -- Strategy A: "Ignore colors" — best single gem × N sockets
    local bisRec = addon.ResolveGemRecommendation()
    local ignoreEP = 0
    if bisRec and bisRec.bis then
        ignoreEP = (bisRec.bis.computedEP or 0) * #socketColors
    end

    -- Strategy B: "Match colors" — best gem per socket + bonus
    local matchGems = {}
    local matchEP = 0
    for _, sc in ipairs(socketColors) do
        local gem, score = FindBestGemForSocket(sc, currentWeights, playerStats, hitCap, expCap, hitType, softCaps)
        table.insert(matchGems, { socketColor = sc, gem = gem, ep = score })
        matchEP = matchEP + score
    end

    -- Add socket bonus EP if all colors matched and bonus is known
    local bonusEP = 0
    if bonusStat and bonusAmount and bonusAmount > 0 then
        local bonusWeight = currentWeights[bonusStat] or 0
        bonusEP = bonusAmount * bonusWeight
        matchEP = matchEP + bonusEP
    end

    -- Compare strategies
    local useColorMatch = matchEP > ignoreEP + 0.01  -- slight threshold to prefer simpler

    return {
        ignoreStrategy = bisRec,
        ignoreEP = ignoreEP,
        matchStrategy = matchGems,
        matchEP = matchEP,
        bonusStat = bonusStat,
        bonusAmount = bonusAmount,
        bonusEP = bonusEP,
        useColorMatch = useColorMatch,
        socketCount = #socketColors,
    }
end

-- =============================================================================
-- Enchant recommendation data — maps slot categories to candidate enchants
-- =============================================================================
local slotEnchantCandidates = {
    ["Head"] = {
        { enchantID = 3817, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 50, ITEM_MOD_CRIT_RATING_SHORT = 20 }, name = { enUS = "Arcanum of Torment", deDE = "Arkanum der Qual" } },
        { enchantID = 3818, stats = { ITEM_MOD_STAMINA_SHORT = 37, ITEM_MOD_DEFENSE_RATING_SHORT = 20 }, name = { enUS = "Arcanum of the Stalwart Protector", deDE = "Arkanum des standhaften Beschützers" } },
        { enchantID = 3819, stats = { ITEM_MOD_SPELL_POWER_SHORT = 30, ITEM_MOD_MANA_REGEN_SHORT = 10 }, name = { enUS = "Arcanum of Blissful Mending", deDE = "Arkanum der seligen Heilung" } },
        { enchantID = 3820, stats = { ITEM_MOD_SPELL_POWER_SHORT = 30, ITEM_MOD_CRIT_RATING_SHORT = 20 }, name = { enUS = "Arcanum of Burning Mysteries", deDE = "Arkanum der brennenden Mysterien" } },
    },
    ["Shoulder"] = {
        { enchantID = 3835, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 120, ITEM_MOD_CRIT_RATING_SHORT = 15 }, name = { enUS = "Greater Inscription of the Axe", deDE = "Große Inschrift der Axt" } },
        { enchantID = 3836, stats = { ITEM_MOD_SPELL_POWER_SHORT = 70, ITEM_MOD_CRIT_RATING_SHORT = 15 }, name = { enUS = "Greater Inscription of the Storm", deDE = "Große Inschrift des Sturms" } },
        { enchantID = 3837, stats = { ITEM_MOD_SPELL_POWER_SHORT = 70, ITEM_MOD_MANA_REGEN_SHORT = 8 }, name = { enUS = "Greater Inscription of the Crag", deDE = "Große Inschrift des Felsgrats" } },
        { enchantID = 3838, stats = { ITEM_MOD_DODGE_RATING_SHORT = 60, ITEM_MOD_DEFENSE_RATING_SHORT = 15 }, name = { enUS = "Greater Inscription of the Pinnacle", deDE = "Große Inschrift des Gipfels" } },
        { enchantID = 3808, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 40, ITEM_MOD_CRIT_RATING_SHORT = 15 }, name = { enUS = "Lesser Inscription of the Axe", deDE = "Geringe Inschrift der Axt" } },
        { enchantID = 3810, stats = { ITEM_MOD_SPELL_POWER_SHORT = 24, ITEM_MOD_CRIT_RATING_SHORT = 15 }, name = { enUS = "Lesser Inscription of the Storm", deDE = "Geringe Inschrift des Sturms" } },
        { enchantID = 3809, stats = { ITEM_MOD_SPELL_POWER_SHORT = 24, ITEM_MOD_MANA_REGEN_SHORT = 8 }, name = { enUS = "Lesser Inscription of the Crag", deDE = "Geringe Inschrift des Felsgrats" } },
        { enchantID = 3811, stats = { ITEM_MOD_DODGE_RATING_SHORT = 20, ITEM_MOD_DEFENSE_RATING_SHORT = 15 }, name = { enUS = "Lesser Inscription of the Pinnacle", deDE = "Geringe Inschrift des Gipfels" } },
    },
    ["Cloak"] = {
        { enchantID = 3722, stats = { ITEM_MOD_AGILITY_SHORT = 22 }, name = { enUS = "Enchant Cloak - Major Agility", deDE = "Umhang verzaubern - Große Beweglichkeit" } },
        { enchantID = 3243, stats = { ITEM_MOD_HASTE_RATING_SHORT = 23 }, name = { enUS = "Enchant Cloak - Greater Speed", deDE = "Umhang verzaubern - Großes Tempo" } },
        { enchantID = 1099, stats = { ITEM_MOD_DEFENSE_RATING_SHORT = 16 }, name = { enUS = "Enchant Cloak - Greater Defense", deDE = "Umhang verzaubern - Große Verteidigung" } },
    },
    ["Chest"] = {
        { enchantID = 3832, stats = { ITEM_MOD_STR_SHORT = 10, ITEM_MOD_AGILITY_SHORT = 10, ITEM_MOD_STAMINA_SHORT = 10, ITEM_MOD_INTELLECT_SHORT = 10, ITEM_MOD_SPIRIT_SHORT = 10 }, name = { enUS = "Enchant Chest - Powerful Stats", deDE = "Brustschutz verzaubern - Mächtige Werte" } },
        { enchantID = 1953, stats = { ITEM_MOD_DEFENSE_RATING_SHORT = 22 }, name = { enUS = "Enchant Chest - Greater Defense", deDE = "Brustschutz verzaubern - Große Verteidigung" } },
    },
    ["Wrist"] = {
        { enchantID = 3850, stats = { ITEM_MOD_SPELL_POWER_SHORT = 30 }, name = { enUS = "Enchant Bracers - Greater Spellpower", deDE = "Armschienen verzaubern - Große Zaubermacht" } },
        { enchantID = 3845, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 50 }, name = { enUS = "Enchant Bracers - Greater Assault", deDE = "Armschienen verzaubern - Großer Angriff" } },
        { enchantID = 3757, stats = { ITEM_MOD_STAMINA_SHORT = 40 }, name = { enUS = "Enchant Bracers - Major Stamina", deDE = "Armschienen verzaubern - Erhebliche Ausdauer" } },
        { enchantID = 3758, stats = { ITEM_MOD_INTELLECT_SHORT = 16 }, name = { enUS = "Enchant Bracers - Greater Intellect", deDE = "Armschienen verzaubern - Große Intelligenz" } },
    },
    ["Hands"] = {
        { enchantID = 3246, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 44 }, name = { enUS = "Enchant Gloves - Greater Assault", deDE = "Handschuhe verzaubern - Großer Angriff" } },
        { enchantID = 3249, stats = { ITEM_MOD_SPELL_POWER_SHORT = 28 }, name = { enUS = "Enchant Gloves - Major Spellpower", deDE = "Handschuhe verzaubern - Erhebliche Zaubermacht" } },
        { enchantID = 3222, stats = { ITEM_MOD_HIT_RATING_SHORT = 20 }, name = { enUS = "Enchant Gloves - Precision", deDE = "Handschuhe verzaubern - Präzision" } },
        { enchantID = 3829, stats = { ITEM_MOD_EXPERTISE_RATING_SHORT = 15 }, name = { enUS = "Enchant Gloves - Expertise", deDE = "Handschuhe verzaubern - Waffenkunde" } },
    },
    ["Legs"] = {
        { enchantID = 3822, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 75, ITEM_MOD_CRIT_RATING_SHORT = 22 }, name = { enUS = "Icescale Leg Armor", deDE = "Eisschuppenbeinrüstung" } },
        { enchantID = 3823, stats = { ITEM_MOD_STAMINA_SHORT = 55, ITEM_MOD_AGILITY_SHORT = 22 }, name = { enUS = "Frosthide Leg Armor", deDE = "Frostbalg-Beinrüstung" } },
        { enchantID = 3719, stats = { ITEM_MOD_SPELL_POWER_SHORT = 50, ITEM_MOD_SPIRIT_SHORT = 20 }, name = { enUS = "Brilliant Spellthread", deDE = "Brillanter Zauberfaden" } },
        { enchantID = 3721, stats = { ITEM_MOD_SPELL_POWER_SHORT = 50, ITEM_MOD_STAMINA_SHORT = 30 }, name = { enUS = "Sapphire Spellthread", deDE = "Saphir-Zauberfaden" } },
        { enchantID = 3325, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 55, ITEM_MOD_CRIT_RATING_SHORT = 15 }, name = { enUS = "Nerubian Leg Armor", deDE = "Nerubische Beinrüstung" } },
        { enchantID = 3720, stats = { ITEM_MOD_SPELL_POWER_SHORT = 35, ITEM_MOD_SPIRIT_SHORT = 20 }, name = { enUS = "Shining Spellthread", deDE = "Leuchtender Zauberfaden" } },
    },
    ["Feet"] = {
        { enchantID = 3824, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 32 }, name = { enUS = "Enchant Boots - Greater Assault", deDE = "Stiefel verzaubern - Großer Angriff" } },
        { enchantID = 1075, stats = { ITEM_MOD_AGILITY_SHORT = 12 }, name = { enUS = "Enchant Boots - Greater Agility", deDE = "Stiefel verzaubern - Große Beweglichkeit" } },
        { enchantID = 1147, stats = { ITEM_MOD_STAMINA_SHORT = 22 }, name = { enUS = "Enchant Boots - Greater Fortitude", deDE = "Stiefel verzaubern - Große Seelenstärke" } },
    },
    ["Weapon"] = {
        { enchantID = 3834, stats = { ITEM_MOD_HIT_RATING_SHORT = 25, ITEM_MOD_CRIT_RATING_SHORT = 25 }, name = { enUS = "Enchant Weapon - Accuracy", deDE = "Waffe verzaubern - Präzision" } },
        { enchantID = 3830, stats = { ITEM_MOD_SPELL_POWER_SHORT = 63 }, name = { enUS = "Enchant Weapon - Exceptional Spellpower", deDE = "Waffe verzaubern - Außergewöhnliche Zaubermacht" } },
        { enchantID = 3844, stats = { ITEM_MOD_SPIRIT_SHORT = 45 }, name = { enUS = "Enchant Weapon - Spirit", deDE = "Waffe verzaubern - Willenskraft" } },
        { enchantID = 3225, stats = { ITEM_MOD_AGILITY_SHORT = 26 }, name = { enUS = "Enchant Weapon - Exceptional Agility", deDE = "Waffe verzaubern - Außergewöhnliche Beweglichkeit" } },
        { enchantID = 2673, stats = { ITEM_MOD_SPELL_POWER_SHORT = 40 }, name = { enUS = "Enchant Weapon - Mighty Spellpower", deDE = "Waffe verzaubern - Mächtige Zaubermacht" } },
    },
    ["2HWeapon"] = {
        { enchantID = 3827, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 110 }, name = { enUS = "Enchant 2H Weapon - Massacre", deDE = "Zweihandwaffe verzaubern - Massaker" } },
        { enchantID = 3828, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 85 }, name = { enUS = "Enchant 2H Weapon - Attack Power", deDE = "Zweihandwaffe verzaubern - Angriffskraft" } },
        -- Also include 1H weapon enchants (2H weapons can use them)
        { enchantID = 3834, stats = { ITEM_MOD_HIT_RATING_SHORT = 25, ITEM_MOD_CRIT_RATING_SHORT = 25 }, name = { enUS = "Enchant Weapon - Accuracy", deDE = "Waffe verzaubern - Präzision" } },
        { enchantID = 3830, stats = { ITEM_MOD_SPELL_POWER_SHORT = 63 }, name = { enUS = "Enchant Weapon - Exceptional Spellpower", deDE = "Waffe verzaubern - Außergewöhnliche Zaubermacht" } },
        { enchantID = 3225, stats = { ITEM_MOD_AGILITY_SHORT = 26 }, name = { enUS = "Enchant Weapon - Exceptional Agility", deDE = "Waffe verzaubern - Außergewöhnliche Beweglichkeit" } },
    },
    ["Shield"] = {
        { enchantID = 1952, stats = { ITEM_MOD_DEFENSE_RATING_SHORT = 20 }, name = { enUS = "Enchant Shield - Defense", deDE = "Schild verzaubern - Verteidigung" } },
        { enchantID = 1071, stats = { ITEM_MOD_INTELLECT_SHORT = 25 }, name = { enUS = "Enchant Shield - Greater Intellect", deDE = "Schild verzaubern - Große Intelligenz" } },
        { enchantID = 3849, stats = { ITEM_MOD_BLOCK_VALUE_SHORT = 40 }, name = { enUS = "Titanium Plating", deDE = "Titaniumüberzug" } },
    },
    ["Ranged"] = {
        { enchantID = 3843, stats = { ITEM_MOD_CRIT_RATING_SHORT = 40 }, name = { enUS = "Heartseeker Scope", deDE = "Herzsucher-Zielfernrohr" } },
        { enchantID = 3608, stats = { ITEM_MOD_HIT_RATING_SHORT = 40 }, name = { enUS = "Sun Scope", deDE = "Sonnen-Zielfernrohr" } },
    },
    ["Ring"] = {
        { enchantID = 3839, stats = { ITEM_MOD_ATTACK_POWER_SHORT = 40 }, name = { enUS = "Enchant Ring - Assault", deDE = "Ring verzaubern - Angriff" } },
        { enchantID = 3840, stats = { ITEM_MOD_SPELL_POWER_SHORT = 23 }, name = { enUS = "Enchant Ring - Greater Spellpower", deDE = "Ring verzaubern - Große Zaubermacht" } },
        { enchantID = 3791, stats = { ITEM_MOD_STAMINA_SHORT = 30 }, name = { enUS = "Enchant Ring - Stamina", deDE = "Ring verzaubern - Ausdauer" } },
    },
}

-- Map itemEquipLoc strings to enchant slot categories
local equipLocToEnchantSlot = {
    ["INVTYPE_HEAD"] = "Head",
    ["INVTYPE_SHOULDER"] = "Shoulder",
    ["INVTYPE_CLOAK"] = "Cloak",
    ["INVTYPE_CHEST"] = "Chest",
    ["INVTYPE_ROBE"] = "Chest",
    ["INVTYPE_WRIST"] = "Wrist",
    ["INVTYPE_HAND"] = "Hands",
    ["INVTYPE_LEGS"] = "Legs",
    ["INVTYPE_FEET"] = "Feet",
    ["INVTYPE_WEAPON"] = "Weapon",
    ["INVTYPE_WEAPONMAINHAND"] = "Weapon",
    ["INVTYPE_WEAPONOFFHAND"] = "Weapon",
    ["INVTYPE_2HWEAPON"] = "2HWeapon",
    ["INVTYPE_SHIELD"] = "Shield",
    ["INVTYPE_RANGED"] = "Ranged",
    ["INVTYPE_RANGEDRIGHT"] = "Ranged",
    ["INVTYPE_THROWN"] = "Ranged",
    ["INVTYPE_FINGER"] = "Ring",
}

local function ScoreEnchantCandidate(enchant, weights, playerStats, hitCap, expCap, hitType, softCaps)
    local totalEP = 0
    for stat, amount in pairs(enchant.stats) do
        local pseudo = { stat = stat, amount = amount }
        totalEP = totalEP + ScoreGemCandidate(pseudo, weights, playerStats, hitCap, expCap, hitType, softCaps)
    end
    return totalEP
end

function addon.ResolveEnchantRecommendation(itemEquipLoc, itemLink)
    local slotCategory = equipLocToEnchantSlot[itemEquipLoc]
    if not slotCategory then return nil end

    local candidates = slotEnchantCandidates[slotCategory]
    if not candidates or #candidates == 0 then return nil end

    local currentWeights = addon.GetCurrentWeights()
    if not currentWeights or not next(currentWeights) then return nil end

    local classData = addon.GetClassData()
    local hitCap, expCap = 0, 0
    local hitType = nil
    if classData then
        hitType = classData["HitRatingType"]
        hitCap, expCap = addon.GetCurrentCapSettings()
    end
    local softCaps = addon.GetCurrentSoftCaps and addon.GetCurrentSoftCaps() or {}

    -- Build player stats
    local playerStats = {}
    for stat, _ in pairs(currentWeights) do
        playerStats[stat] = addon.GetCurrentPlayerStatValue(stat) or 0
    end
    if hitCap > 0 and hitType then
        playerStats["ITEM_MOD_HIT_RATING_SHORT"] = playerStats["ITEM_MOD_HIT_RATING_SHORT"] or (GetCombatRating and GetCombatRating(hitType) or 0)
    end
    if expCap > 0 then
        playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] = playerStats["ITEM_MOD_EXPERTISE_RATING_SHORT"] or (GetCombatRating and GetCombatRating(CR_EXPERTISE) or 0)
    end
    for stat, _ in pairs(softCaps) do
        if not playerStats[stat] then
            playerStats[stat] = addon.GetCurrentPlayerStatValue(stat) or 0
        end
    end

    -- Score all candidates
    local bestEnchant, bestScore = nil, 0
    for _, enchant in ipairs(candidates) do
        local score = ScoreEnchantCandidate(enchant, currentWeights, playerStats, hitCap, expCap, hitType, softCaps)
        if score > bestScore then
            bestScore = score
            bestEnchant = enchant
        end
    end

    if not bestEnchant then return nil end

    -- Score current enchant on the item (if any)
    local currentEnchantEP = 0
    local currentEnchantID = nil
    local isCurrentBiS = false
    if itemLink then
        currentEnchantID = tonumber(itemLink:match("item:%d+:(%d+)"))
        if currentEnchantID and currentEnchantID > 0 then
            local currentStats = enchantData[currentEnchantID]
            if currentStats then
                local tempEnchant = { stats = currentStats }
                currentEnchantEP = ScoreEnchantCandidate(tempEnchant, currentWeights, playerStats, hitCap, expCap, hitType, softCaps)
            end
            isCurrentBiS = (currentEnchantID == bestEnchant.enchantID)
        end
    end

    return {
        best = bestEnchant,
        bestEP = bestScore,
        currentEnchantID = currentEnchantID,
        currentEnchantEP = currentEnchantEP,
        isCurrentBiS = isCurrentBiS,
        hasEnchant = (currentEnchantID ~= nil and currentEnchantID > 0),
    }
end

function addon.GetLocalizedEnchantName(enchant)
    local locale = GetLocale and GetLocale() or "enUS"
    return enchant.name[locale] or enchant.name["enUS"]
end

function addon.GetLocalizedGemName(gem)
    local locale = GetLocale and GetLocale() or "enUS"
    return gem.name[locale] or gem.name["enUS"]
end

local function GetActiveWeightsTable()
    local bracket = addon.GetLevelBracketKey()
    if bracket == "leveling" then
        return levelingWeights
    else
        return endgameWeights
    end
end

addon.SetAllWeights(GetActiveWeightsTable())
addon.SetClassData(addon.GetAllWeights()[class] or { Specs = {""} })

function addon.GetMergedWeights(specName)
    local mergedWeights = {}
    local classData = addon.GetClassData()
    local baseWeights = classData and classData[specName]
    if baseWeights then
        for stat, value in pairs(baseWeights) do
            mergedWeights[stat] = value
        end
    end

    local overrides = addon.GetSpecOverrides(specName, false)
    if overrides then
        for stat, value in pairs(overrides) do
            if type(value) == "number" then
                mergedWeights[stat] = value
            end
        end
    end

    return mergedWeights
end

function addon.GetCurrentPlayerStatValue(stat)
    if not stat then
        return 0
    end

    local classData = addon.GetClassData()
    local hitType = classData and classData["HitRatingType"]

    if stat == "ITEM_MOD_HIT_RATING_SHORT" and hitType then
        return GetCombatRating(hitType)
    end

    if stat == "ITEM_MOD_EXPERTISE_RATING_SHORT" then
        return GetCombatRating(CR_EXPERTISE)
    end

    local total = 0
    for slot = 1, 19 do
        local equippedLink = GetInventoryItemLink("player", slot)
        if equippedLink then
            local equippedStats = addon.GetItemStatsWithEnchantAndGems(equippedLink)
            if equippedStats and type(equippedStats[stat]) == "number" then
                total = total + equippedStats[stat]
            end
        end
    end

    return total
end

function addon.CalculateEP(link)
    if not link then return 0 end
    local stats = addon.GetItemStatsWithEnchantAndGems(link)
    if not stats then stats = {} end

    -- Trinket proc/on-use EP fallback: merge pre-computed passive-equivalent stats
    local itemID = tonumber(link:match("item:(%d+)"))
    if itemID and trinketProcData[itemID] then
        for stat, value in pairs(trinketProcData[itemID]) do
            stats[stat] = (stats[stat] or 0) + value
        end
    end

    local classData = addon.GetClassData()
    local currentWeights = addon.GetCurrentWeights()
    local curHit, curExp = 0, 0
    local hitCap, expCap = 0, 0
    local hitType = nil
    local softCaps = addon.GetCurrentSoftCaps and addon.GetCurrentSoftCaps() or {}

    if classData then
        hitType = classData["HitRatingType"]
        hitCap, expCap = addon.GetCurrentCapSettings()
        if hitType then curHit = GetCombatRating(hitType) end
        if expCap > 0 then curExp = GetCombatRating(CR_EXPERTISE) end
    end

    local totalEP = 0
    local hitCapped = hitCap > 0 and curHit >= hitCap
    local expCapped = expCap > 0 and curExp >= expCap

    for stat, value in pairs(stats) do
        local weight = currentWeights[stat]
        if weight then
            local apply = true
            if stat == "ITEM_MOD_HIT_RATING_SHORT" then
                if hitCapped then
                    apply = false
                end
            end
            if stat == "ITEM_MOD_EXPERTISE_RATING_SHORT" then
                if expCapped then
                    apply = false
                end
            end
            if apply then
                local soft = softCaps[stat]
                if stat == "ITEM_MOD_HIT_RATING_SHORT" or stat == "ITEM_MOD_EXPERTISE_RATING_SHORT" then
                    soft = nil
                end

                if soft and type(soft.cap) == "number" and soft.cap > 0 then
                    local currentStatValue = addon.GetCurrentPlayerStatValue(stat)
                    if currentStatValue >= soft.cap then
                        local softMultiplier = type(soft.multiplier) == "number" and soft.multiplier or 1
                        if softMultiplier < 0 then
                            softMultiplier = 0
                        end
                        weight = weight * softMultiplier
                    end
                end
            end
            if apply then totalEP = totalEP + (value * weight) end
        end
    end

    return totalEP
end

function addon.UpdateActiveWeights()
    local currentLevel = UnitLevel("player")
    local activeWeights = GetActiveWeightsTable()
    if addon.GetAllWeights() ~= activeWeights then
        addon.SetAllWeights(activeWeights)
    end
    addon.SetClassData(addon.GetAllWeights()[class] or { Specs = {""} })
    addon.SetLastDetectedLevel(currentLevel)

    local classData = addon.GetClassData()
    local forcedSpec = addon.GetForcedSpecOverride and addon.GetForcedSpecOverride() or nil

    local function HasSpecName(specName)
        if not specName or specName == "" then
            return false
        end
        for _, existing in ipairs(classData["Specs"] or {}) do
            if existing == specName then
                return true
            end
        end
        return false
    end

    local detectedSpec = nil
    if not forcedSpec then
        local activeGroup = GetActiveTalentGroup and GetActiveTalentGroup() or 1
        local maxPoints, specIndex = -1, 0
        for i = 1, #(classData["Specs"] or {}) do
            local _, _, pointsSpent = GetTalentTabInfo(i, nil, nil, activeGroup)
            if pointsSpent and pointsSpent > maxPoints then
                maxPoints = pointsSpent
                specIndex = i
            end
        end

        if specIndex > 0 and classData["Specs"] and classData["Specs"][specIndex] then
            detectedSpec = classData["Specs"][specIndex]
        end
        addon.SetLastDetectedSpec(detectedSpec)
    end

    local effectiveSpec = nil
    if forcedSpec and HasSpecName(forcedSpec) then
        effectiveSpec = forcedSpec
    else
        effectiveSpec = detectedSpec
    end

    if effectiveSpec then
        addon.SetCurrentSpecName(effectiveSpec)
        addon.SetCurrentWeights(addon.GetMergedWeights(effectiveSpec))
    else
        addon.SetCurrentSpecName("")
        addon.SetCurrentWeights({})
    end
end
